server:
  port: 8888
spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        - id: account-service
          uri: ${ACCOUNT_SERVICE_URL:http://localhost:8080}
          predicates:
            - Path=/api/accounts/**

        - id: watch-service
          uri: ${WATCH_SERVICE_URL:http://localhost:8081}
          predicates:
            - Path=/api/watches/**

        - id: brand-service
          uri: ${BRAND_SERVICE_URL:http://localhost:8082}
          predicates:
            - Path=/api/brands/**

